### ISSUE TITLE
Modelagem do Banco de dados

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#10]
Criar o diagrama da modelagem do banco de dados e colocar no readme e na Wiki do projeto.

**Requisito relacionado:** Não se aplica
**Nome da branch:** modelagem-inicial

**Comment by dalwesley** [comment]
![uml](https://user-images.githubusercontent.com/16858553/94498469-9b952400-01d0-11eb-9485-883f689f4aff.png)
