### ISSUE TITLE
Criar a Apresentação da Sprint 0

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#13]
Criar a Apresentação da Sprint.
Na apresentação deve conter:

- [x] Dizer o nome do projeto, quem faz parte e porque o PI existe (explica o que é o PI, qual a motivação, etc..);
- [x] Um resumo do produto que pensamos em trabalhar + Visão do produto;
- [x] Apresentação dos requisitos de forma resumida;
- [x] Mostrar o Wireframe;

- [x] Expor os requisitos prometidos para a próxima Sprint;

**Requisito relacionado:** Não se aplica
**Nome da branch:** apresentacao

**Comment by andre-custodio** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/blob/master/assets/sprint0.pdf
