### ISSUE TITLE
API de CRUD de Pessoas Físicas

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#18]
Desenvolver uma API no back-end que disponibilize as seguintes funções: criar, editar e deletar um cadastro de pessoa física.
Os campos que devem constar no cadastro são:
* CPF;
* Sexo (M ou F);
* Ano de nascimento
* Cidade
* Estado

**Requisito relacionado:** R01 e R02
**Nome da branch:** crud-pf

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/pull/33
