### ISSUE TITLE
Definir as Personas do Projeto

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#2]
Definir as personas do projeto (pelo menos 10) de acordo com o exemplo:
Persona 1 :João, 26 anos, solteiro, score 300, 4 dívidas registradas, 10 dívidas pagas, estudante de Redes de Computadores, mora sozinho.
Persona 2 : ...
Salvar na wiki do projeto com o título: Persona.

**Requisito relacionado:** Não se aplica
**Nome da branch:** Persona

**Comment by andre-custodio** [comment]
Ainda passará por refinamento assim que finalizada a equação do SCORE.
https://github.com/pi-fatec-bd/cadastro-mais/wiki/Personas
