### ISSUE TITLE
Calcular Score

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#20]
Criar uma rota da API no backend que calcula e informa o score de uma pessoa Física.

_- Essa issue depende da issue #19_ 
_A issue #21 depende da conclusão dessa issue_

Requisito relacionado: R03. e R04 e R09
Nome da branch: api-score

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/pull/35

**Comment by AndreLars** [comment]
Reabrindo para calcular o score efetivamente
