### ISSUE TITLE
Consulta de dados de Pessoa Física

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#21]
Criar uma rota na API que retorna os dados de uma pessoa física (endereço, informações de contato, dívidas e pagamentos realizados).
Obs: É necessário verificar se a pessoa que está fazendo a requisição tem autorização para acessar quais desses dados.

_Essa issue depende da issue #20._

**Requisito relacionado:** R05. e R10.
**Nome da branch:** api-consulta-dados

**Comment by AndreLars** [comment]
Reabrindo para fazer realmente a issue que não foi feita na sprint 1
