### ISSUE TITLE
API de CRUD de Pessoas Jurídicas

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#22]
Desenvolver uma API no back-end que disponibilize as seguintes funções: criar, editar e deletar um cadastro de pessoa juridica.
Os campos que devem constar no cadastro são:

CNPJ;
Cidade
Estado
Senha

**Requisito relacionado:** R15 e R16
**Nome da branch:** crud-pj

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/pull/34
