### ISSUE TITLE
Tela de Consulta de Score de Terceiros

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#27]
- [x] consultar um score de um terceiro e exibir na tela;

_Caso a issue #20 ainda não esteja completa, pergunte para o responsável apenas a rota que deve ser feito a requisição._

**Requisito relacionado:** R09
**Nome da branch:** tela-consulta-terceiros

**Comment by dalwesley** [comment]
incluído a tela de consulta do score
