### ISSUE TITLE
Tela de Consulta de dados de Terceiros

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#28]
- [x] consultar um score de um terceiro e exibir na tela;

- [x] Criar um menu na tela principal em que a pessoa pode escolhe qual tipo de consulta à terceiros ela quer fazer: Simples (somente o score) ou completa (score + dados);

_Essa issue depende da issue #26_ 
_Caso a issue #21  ainda não esteja completa, pergunte para o responsável apenas a rota que deve ser feito a requisição._

**Requisito relacionado:** R10
**Nome da branch:** tela-dados-terceiros

**Comment by dalwesley** [comment]
incluído a tela de sonsulta do score com a possibilidade de consulta detalhada ou simples
