### ISSUE TITLE
Rota de bloqueio de visualização de dados

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#37]
Criar uma rota no backend em que a pessoa física possa bloquear um ou todos os CPFs e CNPJs de verem os dados da mesma. 

**Requisito relacionado:** R07 e R08 
**Nome da branch:** bloqueia-visualizacao

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/pull/49
