### ISSUE TITLE
Backend - Persistência do Login

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#43]
Persistir os dados do login no backend para fazer a verificação de login para acesso de páginas restritas.

**Requisito relacionado:** Não se aplica 
**Nome da branch:** persistencia-login

**Comment by AndreLars** [comment]
Recomendo separar as duas frentes
No front precisa ser implementado algum tipo de storage persistindo a sessão do usuário, seja session storage ou local storage
Além da autorização no backend com algum token (por exemplo JWT) que deverá ser guardado no front e enviado nas requisições necessárias para fazer requests nas apis

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/cadastro-mais/pull/49
