### ISSUE TITLE
Número Contrato tabela OPERACOES

### ISSUE THREAD

**Issue by AndreLars** [pi-fatec-bd/semaforo-consumidor#45]
A coluna OPE_NUM_CON da tabela OPERACOES está com dados inconsistentes em relação às outras tabelas.

Essa coluna seria a base para fazer join com MOVIMENTOS e PAGAMENTOS. Porém os dados preenchidos na tabela OPERACOES não batem com nenhuma outra tabela. 

Precisa-se perguntar para o cliente e outros grupos se estão na mesma situação. Isso impacta a entrega da issue: https://github.com/pi-fatec-bd/cadastro-mais/issues/21

**Comment by AndreLars** [comment]
Resposta do cliente 23/10

![image](https://user-images.githubusercontent.com/26588283/97062456-5961c700-1571-11eb-9cdd-57dbe1823515.png)

**Comment by andre-custodio** [comment]
Recebido novo set de dados, aparentemente corrigido.
![image](https://user-images.githubusercontent.com/54409069/97646487-996ff080-1a2e-11eb-9f1c-926a9be0800d.png)
