### ISSUE TITLE
Tela de Cadastros de Desejo de Produtos

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#57]
Desenvolver uma tela de cadastro de desejo de produtos.
- [ ] Campos: Nome do Produto, Categoria do Item, Descrição.
- [ ] Integração com o Back-End

**requisitos relacionados:** R12, R13 e R33
**nome da branch:** cadastro-desejos

**Comment by dalwesley** [comment]
finalizado e commitado
