### ISSUE TITLE
Criar tabela de produtos no banco de Dados

### ISSUE THREAD

**Issue by felipemessi** [pi-fatec-bd/semaforo-consumidor#61]
Criar o script sql de criação da tabela de produtos e suas relações.

**Requisito relacionado:** R12
**Nome da branch:** bd-produtos

**Comment by AndreLars** [comment]
https://github.com/pi-fatec-bd/semaforo-consumidor/pull/70
Criado os scripts de criação das tabelas
Próximos passos:
 - Definir as categorias de produtos, recomendo pelo menos 7 categorias diferentes para ter variedade
